services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: planTripTogether
      POSTGRES_USER: ptt
      POSTGRES_PASSWORD: ptt
    ports: ["5433:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata: